server:
  port: 9000

spring:
  liquibase:
    enabled: false
  application:
    name: igodating-questionary-service
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 50
    url: jdbc:postgresql://localhost:5432/igodating?current_schema=questionary
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        default_schema: questionary
        dialect: org.hibernate.dialect.PostgreSQLDialect

model:
  path: /lm-model/
  url: djl://ai.djl.huggingface.pytorch/sentence-transformers/all-MiniLM-L6-v2

whitening-matrix:
  selection-limit: 50000
  shrinkage-lambda: 0.1

scheduling:
  whitening-matrix-delay: 10000000
  vector-init-delay: 10000
  vector_init_limit: 100