create table chat_restrictions(
    id           bigserial      primary key,
    type         varchar(50)    not null unique,
    duration     interval,
    "limit"      int            not null,
    description  varchar,
    active       bool           default true,
    created_at   timestamptz    not null default now(),
    updated_at   timestamptz    not null default now()
);

insert into chat_restrictions (type, duration, "limit")
VALUES ('COUNT_CHAT_MESSAGES', interval '1 minute', 30),
       ('SIZE_MESSAGE_ATTACHMENTS', null, 10),
       ('COUNT_MESSAGE_ATTACHMENTS', null, 2);

CREATE TRIGGER set_updated_at_to_now_trigger
    BEFORE UPDATE
    ON chat_restrictions
    FOR EACH ROW
EXECUTE PROCEDURE set_updated_at_to_now();

comment on table chat_restrictions is 'Table with chat restrictions';
comment on column chat_restrictions.id is 'Unique identifier. Autogenerated';
comment on column chat_restrictions.type is 'Type of restriction';
comment on column chat_restrictions.duration is 'Time period for restriction';
comment on column chat_restrictions.limit is 'Limit for restriction. Can work with duration. Fof example: 30 messages in 1 minute';