/**
 * Chat service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatInfoByUserShared } from './chatInfoByUserShared';

export interface ChatSummaryResponse { 
    chatId2ChatInfo?: { [key: string]: ChatInfoByUserShared; };
    chatType2totalUnreadMessages?: { [key: string]: number; };
}