comment on table allowed_file_extensions is 'Table with allowed files extensions';
comment on column allowed_file_extensions.id is 'Unique identifier. Autogenerated';
comment on column allowed_file_extensions.extension is 'file extension';
comment on column allowed_file_extensions.created_at is 'When created. Default now()';
comment on column allowed_file_extensions.updated_at is 'When updated. Default now(). Set to ''now()'' after every update. See ''set_updated_at_to_now()'' function';
comment on column allowed_file_extensions.operation_name is 'See enum FileOperation in chat service. Available values: CHAT';